from __future__ import absolute_import
import math

import numpy as np

from ._revolved import revolved
from mmcore.geom._nurbs_construct import circle


def torus(major_radius=1.0, minor_radius=0.25,
          start_angle=0.0, end_angle=2 * math.pi,
          center=None, normal=None, xaxis=None, yaxis=None):
    """
    Generates a torus as a NURBS surface.

    Parameters:
      major_radius : float
          The radius of the major (sweeping) circle: the distance from the torus center
          to the center of the tube.
      minor_radius : float
          The radius of the tube (i.e. the profile curve).
      start_angle, end_angle : float
          The angular interval (in radians) over which the torus is generated.
          For a full torus use (0, 2*pi).
      center : array-like of 3 floats, optional
          The center of the torus (i.e. the center of the major circle). Defaults to [0,0,0].
      normal : array-like of 3 floats, optional
          The normal vector defining the plane of the major circle.
      xaxis, yaxis : array-like of 3 floats, optional
          The in‑plane coordinate system for the major circle. If provided, these are used directly.
          Otherwise, if a normal is provided, an orthonormal basis is constructed.
          If neither is provided, defaults to the xy‑plane.

    Returns:
      A NURBSSurfaceTuple representing the torus.

    Process:
      1. Build the axis for revolution from the torus center along the given normal.
      2. Construct the profile (tube) circle. Its center is computed as:
             profile_center = center + major_radius * xaxis
         and its normal is calculated as the normalized vector (profile_center - center),
         so that the profile circle’s plane is perpendicular to the major circle’s plane.
      3. Generate the revolved surface from the profile curve.
    """
    # --- Determine the torus coordinate system ---
    if center is None:
        center = np.array([0.0, 0.0, 0.0])
    else:
        center = np.array(center, dtype=float)

    # Option 1: use provided xaxis and yaxis if available.
    if (xaxis is not None) and (yaxis is not None):
        xaxis = np.array(xaxis, dtype=float)
        yaxis = np.array(yaxis, dtype=float)
        xaxis = xaxis / np.linalg.norm(xaxis)
        yaxis = yaxis / np.linalg.norm(yaxis)
    # Option 2: if normal is provided, generate an in‑plane basis.
    elif normal is not None:
        normal = np.array(normal, dtype=float)
        normal = normal / np.linalg.norm(normal)
        # Construct an in‑plane xaxis.
        if abs(normal[0]) < 1e-6 and abs(normal[1]) < 1e-6:
            xaxis = np.array([1.0, 0.0, 0.0])
        else:
            xaxis = np.cross([0, 0, 1], normal)
            if np.linalg.norm(xaxis) < 1e-6:
                xaxis = np.array([1.0, 0.0, 0.0])
            else:
                xaxis = xaxis / np.linalg.norm(xaxis)
        # yaxis is chosen to complete the right-handed system.
        yaxis = np.cross(normal, xaxis)
        yaxis = yaxis / np.linalg.norm(yaxis)
    else:
        # Default to the xy-plane.
        xaxis = np.array([1.0, 0.0, 0.0])
        yaxis = np.array([0.0, 1.0, 0.0])
        normal = np.cross(xaxis, yaxis)
        normal = normal / np.linalg.norm(normal)

    # --- Build the axis for the revolution ---
    # The torus is generated by revolving the profile curve about an axis that passes through 'center'
    # in the direction of 'normal'.
    S = center.copy()  # base point on the axis
    T = normal.copy()  # direction of the axis (normalized)
    axis = (S, S + T)  # the axis expressed as two points

    # --- Generate the profile (tube) curve ---
    # The profile curve (a circle) is positioned at:
    profile_center = center + major_radius * xaxis

    # CORRECT THE PROFILE CIRCLE ORIENTATION:
    # The profile circle’s plane should be perpendicular to the radial direction from
    # the torus center to the profile center. Hence its normal is:

    profile_normal = -yaxis

    # Choose an in‑plane basis for the profile circle.
    # A natural choice is to let the first in‑plane direction be T (the torus’s axis);
    # then the second is the cross of profile_normal and T.
    profile_xaxis = T.copy()
    profile_yaxis = np.cross(profile_normal, T)
    profile_yaxis = profile_yaxis / np.linalg.norm(profile_yaxis)

    # Now generate the profile curve (a full circle representing the tube cross‑section)
    profile_curve = circle(radius=minor_radius,
                           start_angle=0.0,
                           end_angle=2 * math.pi,
                           center=profile_center,
                           normal=profile_normal,  # Use the computed profile normal.
                           xaxis=profile_xaxis,
                           yaxis=profile_yaxis)

    # --- Create the torus as a revolved surface ---
    # The profile is swept about the torus axis using the supplied angular interval.
    torus_surface = revolved(profile_curve, axis, (start_angle, end_angle))

    return torus_surface
