GET http://localhost:7711/fetch/sw_wall

###
GET http://localhost:7711/keys

###
POST https://viewer.contextmachine.online/cxm/api/v2/mfb_sw_l2/params/node/mfb_sw_l2_panels
Content-Type: application/json

{
  "name": "mfb_sw_l2_panels",
  "masks": {
    "projmask": true,
    "cut_mask": false,
    "demo": false
  }
}

###
POST http://localhost:7711/params/node/test_sweep
Content-Type: application/json

{
  "path": {
    "radius": 100,
    "high": 420,
    "pitches": 16
  },
  "color": [70, 170, 150],
  "opacity": 0.5
}

###
POST https://viewer.contextmachine.online/cxm/api/v2/mfb_sw_l2/params/node/test_loft_b
Content-Type: application/json

{
  "path": {
    "points": {
      "a": {
        "x": -15,
        "y": 4,
        "z": 15
      },
      "b": {
        "x": 0,
        "y": 24,
        "z": 10
      },
      "c": {
        "x": 15,
        "y": 4,
        "z": 15
      }
    },
    "num": 50,
    "color": [150, 75, 75],
    "secondary_color": [200, 100, 100]
  },
  "color": [150, 150, 160]
}

###
GRAPHQL localhost:7711/graphql

{
sw_wall
}

