from typing import *


class Props:
    def __init__(self, *args: Iterable[Any], uuid: Optional[str], **kwargs: dict): ...

    def __getitem__(self, item) -> Any: ...

    def __setitem__(self, item, val) -> None: ...

    def keys(self) -> Generator[str, None, None]: ...


def props_to_dict(props: Props) -> dict: ...
