apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mmcore

  name: mmcore
  namespace: default
spec:
    containers:
    - image:
        cr.yandex/crpfskvn79g5ht8njq0k/cxm-viewer:latest
      imagePullPolicy: Always
    name: cxmviewer
    env:

        - name:
            NODE_ENV
          value: "development"

        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cxmviewer
  name: cxmviewer
  namespace: default
spec:
  ports:
  - protocol: TCP

    port: 80
    targetPort: 3000
  selector:
    app: cxmviewer

  type: LoadBalancer

