service:
  name: rhpyc
  attributes:
    port: 7778
    mode: threaded
    allow_setattr: true
    allow_delattr: true
    allow_pickle: true
  configs:
    hosts:
      - localhost
      - 92.53.64.197



