name: upload-to-pypi

on:
  
  workflow_run:
    workflows:
      - poetry-build # Name of the triggering workflow
    types:
      - completed
    branches:
      - 'tiny'

jobs:
  upload_pypi:
    runs-on: ubuntu-latest
    environment:
      name: poetry
      url: https://pypi.org/p/mmcore

    permissions:
      id-token: write

    steps:

      - uses: actions/checkout@v4
      - name: Debug artifact name
        run: |
          echo "Artifact name: ${{github.triggering_actor.steps.modify_name.outputs.new_wheelfile_name}}"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{github.triggering_actor.steps.modify_name.outputs.new_wheelfile_name}}
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
